# Generated by Django 3.2.5 on 2021-09-01 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(max_length=100000, verbose_name='本文')),
                ('created_by', models.CharField(max_length=20, null=True, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新時間')),
                ('fav', models.ManyToManyField(blank=True, related_name='article_fav', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connection',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント')),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.CharField(max_length=100, null=True, verbose_name='投稿者')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_create.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
