"""
Django settings for ShareCreateApp project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%)bvteg)z+h6eu#z+be2zfeq*iopoa!^i&2=6521$%!$5xz*8_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SUMMERNOTE_THEME = 'bs4'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 以下2行は自分で作ったアプリ
    'share_create.apps.ShareCreateConfig',
    'accounts.apps.AccountsConfig',
    'django_bootstrap5',
    # allauth使う時に必要(以下4行)
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # social login に使う
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    # summernote
    'django_summernote',
    # タグ
    'taggit',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ShareCreateApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShareCreateApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# プロジェクト直下のstaticディレクトリ参照
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    #     管理画面にユーザーネームでログインするのに必要
    'django.contrib.auth.backends.ModelBackend',
    #     allauthを使う時に必要
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# メディアファイルの有効化
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ユーザ登録確認メール送信
ACCOUNT_EMAIL_VARIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = 'True'

# コンソールのユーザ登録確認メールを見るために必要
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# カスタムユーザーモデルを使用
AUTH_USER_MODEL = 'accounts.User'

# ログイン、ログアウト時の遷移先の設定
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'accounts:home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'accounts:home'

# ログアウト確認なしでワンクリックでログアウト
ACCOUNT_LOGOUT_ON_GET = True

IMAGE_ROOT = os.path.join(BASE_DIR, 'images/article_images')
IMAGE_URL = '/images/'
SUMMERNOTE_CONFIG = {
    #     'iframe': True,
    #
    'summernote': {
        'width': '100%',
        'height': '1500',
    },
    #     'toolbar': [
    #         ['font', ['bold', 'underline', 'clear']],
    #         ['para', ['ul', 'ol', 'paragraph']],
    #     ],
}
